# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=7)),
                ('face_complexion', models.CharField(choices=[('Dark', 'dark'), ('Fair', 'fair'), ('Pimples', 'pimples'), ('OLIVE', 'olive'), ('Spots', 'spots'), ('Pale', 'pale'), ('Sunburnt', 'sunburnt')], default='Dark', max_length=15)),
                ('face_shape', models.CharField(choices=[('Round', 'round'), ('Angular', 'angular'), ('Oval', 'oval'), ('Long', 'long'), ('Thin', 'thin'), ('Square', 'square'), ('Freckled', 'freckled')], default='Round', max_length=15)),
                ('hair', models.CharField(choices=[('Black', 'black'), ('blond', 'blonde'), ('Fair', 'fair'), ('Red', 'red'), ('Brown', 'brown'), ('Grey', 'grey'), ('White', 'white'), ('Long', 'long'), ('Short', 'short'), ('Curly', 'curly'), ('Straight', 'straight'), ('Bald', 'bald')], default='Black', max_length=15)),
                ('cheek', models.CharField(choices=[('Chubby', 'chubby'), ('Wide', 'wide'), ('Plump', 'pimples'), ('Hollow', 'hollow'), ('Sunken', 'sunken'), ('Dimples', 'dimples'), ('Blushing', 'blushing'), ('Pink', 'pink')], default='Chubby', max_length=15)),
                ('ear', models.CharField(choices=[('Curving', 'curving'), ('Pointed', 'pointed'), ('Floppy', 'floppy')], default='Curving', max_length=15)),
                ('eyelashes', models.CharField(choices=[('Short', 'short'), ('Winged', 'winged'), ('Straight', 'straight'), ('Thin', 'thin'), ('Artificial', 'artificial'), ('Thick', 'thick'), ('Long', 'long'), ('Curling', 'curling')], default='Short', max_length=15)),
                ('eyebrow', models.CharField(choices=[('Bushy', 'bushed'), ('Thick', 'thick'), ('Raised', 'raised'), ('Pencilled', 'pencilled')], default='Bushy', max_length=15)),
                ('eyes', models.CharField(choices=[('Brown', 'brown'), ('Black', 'black'), ('Blue', 'blue'), ('Hazel', 'hazel'), ('Blood-shot', 'blood-shot')], default='Brown', max_length=15)),
                ('nose', models.CharField(choices=[('Small', 'small'), ('Big', 'big'), ('Pointed', 'pointed')], default='Small', max_length=15)),
            ],
        ),
    ]
